[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Backend Service
[[services]]
name = "backend"
source = "backend"

[services.variables]
NODE_ENV = "production"
PORT = "3001"

[services.build]
buildCommand = "npm ci && npm run build"
startCommand = "npm start"

[services.healthcheck]
path = "/health"
port = 3001
initialDelaySeconds = 10
periodSeconds = 10

# Frontend Service  
[[services]]
name = "frontend"
source = "frontend"

[services.variables]
NODE_ENV = "production"

[services.build]
buildCommand = "npm ci && npm run build"
startCommand = "npm start"

[services.healthcheck]
path = "/api/health"
port = 3000
initialDelaySeconds = 15
periodSeconds = 10

# Database
[[services]]
name = "database"
source = "postgres"

[services.variables]
POSTGRES_DB = "railway"
POSTGRES_USER = "postgres"